name: CI intrale-parent

on:
  push:
    branches: [ main ]
  repository_dispatch:
jobs:
  build: 

    runs-on: ubuntu-latest

    steps:
    - name: Download source code
      uses: actions/checkout@v3
    - name: JDK Setup
      uses: actions/setup-java@v2
      with:
          java-version: '11' # The JDK version to make available on the path.
          distribution: 'temurin'
          java-package: jdk # (jre, jdk, or jdk+fx) - defaults to jdk
          architecture: x64 # (x64 or x86) - defaults to x64    
    - name: Version definition
      run: |
         echo "VERSION=0" >> $GITHUB_ENV
         echo "FEATURE=1" >> $GITHUB_ENV
    - name: Get Compile Number
      run: |
         COMPILE_NUMBER=`cat ./compile.number`
         echo "COMPILE_NUMBER=$(($COMPILE_NUMBER+1))" >> $GITHUB_ENV
    - name: Version target definition
      env:
        VERSION: ${{ env.VERSION }}
        FEATURE: ${{ env.FEATURE }}
        COMPILE_NUMBER: ${{ env.COMPILE_NUMBER }}
      run: |
        echo "VERSION_TARGET=${VERSION}.${FEATURE}.${COMPILE_NUMBER}" >> $GITHUB_ENV
    - name: Tag definition
      env:
        VERSION: ${{ env.VERSION }}
        FEATURE: ${{ env.FEATURE }}
        COMPILE_NUMBER: ${{ env.COMPILE_NUMBER }}    
      run: |
        echo "TAG=${VERSION}_${FEATURE}_${COMPILE_NUMBER}" >> $GITHUB_ENV
    - name: Override compile number
      env:
        COMPILE_NUMBER: ${{ env.COMPILE_NUMBER }}    
      run: |
        echo "Contenido compile.number"
        cat ./compile.number
        echo "Variable COMPILE NUMBER:${COMPILE_NUMBER} => ./compile.number"
        echo "${COMPILE_NUMBER}" > ./compile.number
        echo "Contenido compile.number sobreescrito"
        cat ./compile.number
    - name: Commit files
      env:
        VERSION_TARGET: ${{ env.VERSION_TARGET }}    
      run: |
        git config --local user.email "github-actions@users.noreply.github.com"
        git config --local user.name "github-actions"
        git commit -m "[bot]Compile version ${VERSION_TARGET}" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
    - name: Save VER_PARENT
      uses: hmanzur/actions-set-secret@v2.0.0
      with:
        name: 'VER_PARENT'
        value: ${{ env.VERSION_TARGET }}
        repository: 'intrale'
        token: ${{ secrets.MAVEN_SERVER_PASSWORD }}
        org: true   
        visibility: 'all'        
    - name: Deploy to Github Package Registry
      env:
        MAVEN_SERVER_USERNAME: ${{ secrets.MAVEN_SERVER_USERNAME }}
        MAVEN_SERVER_PASSWORD: ${{ secrets.MAVEN_SERVER_PASSWORD }}
      run: |
        sed -i "s/DEV_PARENT/${VERSION_TARGET}/gi" pom.xml
        mkdir -p ~/.m2
        echo "<settings><servers><server><id>github</id><username>${MAVEN_SERVER_USERNAME}</username><password>${MAVEN_SERVER_PASSWORD}</password></server></servers></settings>" > ~/.m2/settings.xml
        mvn -e -X deploy
    - name: Tag Branch  
      uses: rickstaa/action-create-tag@v1
      with:
        tag: "VER_${{ env.TAG }}"
        message: "VER_${{ env.TAG }}"
    - name: Delete old packages
      uses: actions/delete-package-versions@v3
      with:
        owner: 'llarreta'
        repo: 'intrale'
        package-name: 'ar.com.intrale.parent'
        min-versions-to-keep: 3
        token: ${{ secrets.MAVEN_SERVER_PASSWORD }}        