name: Java CI

on:
  push:
    branches: [ main ]

jobs:
  build: 

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
          java-version: '11' # The JDK version to make available on the path.
          java-package: jdk # (jre, jdk, or jdk+fx) - defaults to jdk
          architecture: x64 # (x64 or x86) - defaults to x64
    - name: Deploy to Github Package Registry
      env:
        ACTUAL_VERSION: ${{ secrets.ACTUAL_VERSION }}
        VERSION_PREFIX: ${{ secrets.VERSION_PREFIX }}
        MAVEN_SERVER_USERNAME: ${{ secrets.MAVEN_SERVER_USERNAME }}
        MAVEN_SERVER_PASSWORD: ${{ secrets.MAVEN_SERVER_PASSWORD }}
      run: |
        mkdir -p ~/.m2
        echo "ACTUAL_VERSION: ${ACTUAL_VERSION}"
        echo ::set-env name=NEW_VERSION::$(($ACTUAL_VERSION+1))
        echo "NEW_VERSION: ${NEW_VERSION}"
        echo ::set-env name=VERSION::$(($VERSION_PREFIX+$NEW_VERSION))
         echo "VERSION: ${VERSION}"
        echo "<settings><servers><server><id>github</id><username>${MAVEN_SERVER_USERNAME}</username><password>${MAVEN_SERVER_PASSWORD}</password></server></servers></settings>" > ~/.m2/settings.xml
        mvn deploy
    - uses: actions/delete-package-versions@v1
      with:
        owner: 'llarreta'
        repo: 'intrale'
        package-name: 'ar.com.intrale.cloud.parent'
        num-old-versions-to-delete: 1
        token: ${{ secrets.MAVEN_SERVER_PASSWORD }}
